# Generated by Django 5.1.3 on 2024-11-11 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=80, unique=True, verbose_name='Nome do Fornecedor')),
                ('supplier_cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CNPJ do Fornecedor')),
                ('supplier_phone_number', models.CharField(max_length=11, unique=True, verbose_name='Telefone do Fornecedor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data da Última Alteração')),
                ('supplier_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Empresa da qual é Fornecedor')),
            ],
            options={
                'ordering': ['supplier_name'],
            },
        ),
    ]
