# Generated by Django 5.1.3 on 2024-11-07 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=80, unique=True, verbose_name='Nome do Cliente')),
                ('client_cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ do Cliente')),
                ('client_phone_number', models.CharField(max_length=11, unique=True, verbose_name='Telefone do Cliente')),
                ('client_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Empresa da qual é cliente')),
            ],
            options={
                'ordering': ['client_name'],
            },
        ),
    ]
