# Generated by Django 5.1.3 on 2024-11-20 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('bank_accounts', '0002_bankaccount_created_at_bankaccount_updated_at'),
        ('clients', '0002_client_created_at_client_updated_at'),
        ('companies', '0002_costcenter'),
        ('suppliers', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Valor da Transação')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição da Transação')),
                ('transaction_type', models.IntegerField(choices=[(0, 'Saída'), (1, 'Entrada')], default=1, verbose_name='Tipo de Categoria')),
                ('creation_date', models.DateTimeField(verbose_name='Data de Criação da Transação no sistema a pagar ou a receber')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Operação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data da última atualização')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank_accounts.bankaccount', verbose_name='Conta bancária utilizada para a transação')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.client', verbose_name='Cliente envolvido na Transação')),
                ('company_associated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.usercompany', verbose_name='Compania envolvida')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.costcenter', verbose_name='Centro de Custo envolvido na Transação')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier', verbose_name='Fornecedor envolvido na Transação')),
                ('transaction_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.transactioncategory', verbose_name='Categoria da Transação')),
            ],
        ),
    ]
