# Generated by Django 5.1.3 on 2024-11-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CNPJ da empresa')),
                ('company_address', models.TextField(blank=True, null=True, verbose_name='Endereço da Empresa')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefone da Empresa')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email da empresa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data da última alteração')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro da empresa')),
            ],
        ),
    ]
