# Generated by Django 5.1.3 on 2024-11-14 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Centro de Custo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do Centro de Custo e suas atribuições')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Compania Associada')),
            ],
            options={
                'verbose_name': 'Centros de Custo',
                'ordering': ['name'],
            },
        ),
    ]
