# Generated by Django 5.1.3 on 2024-11-12 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=50, verbose_name='Nome do Banco')),
                ('account_balance', models.FloatField(default=0, verbose_name='Saldo da Conta')),
                ('agency_number', models.CharField(max_length=4, verbose_name='Número da Agência Bancária')),
                ('account_number', models.CharField(max_length=20, verbose_name='Número da Conta')),
                ('account_type', models.CharField(choices=[('CC', 'Conta Corrente'), ('CP', 'Conta Poupança'), ('CPG', 'Conta Pagamento'), ('CI', 'Conta de Investimentos'), ('CE', 'Conta Empresarial')], default='CE', max_length=60, verbose_name='Tipo de conta bancária')),
                ('account_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Empresa proprietária da conta')),
            ],
            options={
                'verbose_name': 'Contas Bancárias',
                'ordering': ['bank'],
            },
        ),
    ]
